### ISSUE TITLE
Installation Error - Hardcoded Path in Manifest

### ISSUE THREAD

**Issue by GarrettMooney** [StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl#2]
# Code in question
https://github.com/StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl/blob/1e6954938e3ce304b85881e14eceb796b06c0c38/Manifest.toml#L1182

The above line produces a `TypeError` when I try to `instantiate` the 📦  environment due to the hardcoded local path.

 It is likely that the below line will produce a similar error.

https://github.com/StatisticalRethinkingJulia/StatisticalRethinkingTuring.jl/blob/1e6954938e3ce304b85881e14eceb796b06c0c38/Manifest.toml#L440

# Error
Here is the `TypeError` produced on a Mac:

```julia
ERROR: TypeError: in typeassert, expected VersionNumber, got a value of type Pkg.Types.VersionSpec
Stacktrace:
 [1] load_urls(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/sha
re/julia/stdlib/v1.5/Pkg/src/Operations.jl:510
 [2] #download_source#54 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:68
6 [inlined]
 [3] download_source at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:685 [i
nlined]
 [4] instantiate(::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Pkg.BinaryPlatforms.MacOS,
 kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/julia/buildbot/worker/package_macos64/buil
d/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:875
 [5] instantiate(::Pkg.Types.Context) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API
.jl:795
 [6] #instantiate#169 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791 [inlined
]
 [7] instantiate() at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/API.jl:791
 [8] do_cmd!(::Pkg.REPLMode.Command, ::REPL.LineEditREPL) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/std
lib/v1.5/Pkg/src/REPLMode/REPLMode.jl:401
 [9] do_cmd(::REPL.LineEditREPL, ::String; do_rethrow::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/
stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:382
 [10] do_cmd at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:377 [in
lined]
 [11] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL,REPL.LineEdit.Prompt})(::REPL.LineEdit.MIState, ::Base.GenericIOBuffer{Array{UI
nt8,1}}, ::Bool) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Pkg/src/REPLMode/REPLMode.jl:546
 [12] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [13] invokelatest at ./essentials.jl:709 [inlined]
 [14] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/julia/buildbo
t/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2355
 [15] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/juli
a/stdlib/v1.5/REPL/src/REPL.jl:1144
 [16] (::REPL.var"#38#42"{REPL.LineEditREPL,REPL.REPLBackendRef})() at ./task.jl:356
```

**Comment by goedman** [comment]
Hi Garett, my apologies for that, should be fixed now in the repo.

You could also try to go into Pkg mode ( `julia> ]` ) and  `free StatisticalRethinking` followed by ` free Formatting`. and then  press the `<return key>` to get back to Julia mode.

The problem is that Formatting.jl is not compatible with Julia 1.6 yet, there is a patch but not released, so I force it to use the unreleased version of Formatting.jl v1.4.2 to test on Julia 1.6-DEV.

Let me know if either of above solutions works (releasing these kinds of projects is new for me as well!).

**Comment by GarrettMooney** [comment]
Hi Rob, thanks for the fix!

A `git pull` resolved things.

Interestingly, the error persisted on the older commit (`1e695`) when trying `free` sequentially on the two 📦 s. It was resolved by a combined `free StatisticalRethinking Formatting`

**Comment by goedman** [comment]
Interesting. Hmm, need to think about that. I'm also a bit unsure if `instantiate` is actually necessary. Thanks for the update,

**Comment by GarrettMooney** [comment]
Oh, realizing I didn't communicate that correctly 🤦 :

A type error occurred at each sequential `free` attempt:

![Screen Shot 2020-11-29 at 2 44 27 PM](https://user-images.githubusercontent.com/4910020/100551906-b841ec80-3251-11eb-821e-38c7fce2c93e.png)

The joint command `free StatisticalRethinking Formatting` appears to update both the `Project.toml` and `Manifest.toml` as desired:

![Screen Shot 2020-11-29 at 2 55 46 PM](https://user-images.githubusercontent.com/4910020/100552154-4cf91a00-3253-11eb-93a6-3f8d6088fd7d.png)
 
and the subsequent `instantiate` doesn't do anything.
